// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrchestratorService.Data;

#nullable disable

namespace OrchestratorService.Migrations
{
    [DbContext(typeof(OrchestratorContext))]
    [Migration("20260114091631_AddAdapterConfig")]
    partial class AddAdapterConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrchestratorService.Models.ActionAdapterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdapterName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AuthToken")
                        .HasColumnType("longtext");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DefaultHeadersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ActionAdapterConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdapterName = "N8n",
                            BaseUrl = "http://localhost:5678/webhook",
                            DefaultHeadersJson = "{}",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("OrchestratorService.Models.WorkflowDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConditionCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContextProfile")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityType")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OnMatchActionsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("OnNoMatchActionsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("RuleSet")
                        .HasColumnType("longtext");

                    b.Property<string>("TriggerConditionJson")
                        .HasColumnType("longtext");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TriggerKey")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("OrchestratorService.Models.WorkflowExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Logs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MembershipId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkflowDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("WorkflowExecutions");
                });

            modelBuilder.Entity("OrchestratorService.Models.WorkflowExecution", b =>
                {
                    b.HasOne("OrchestratorService.Models.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
